### ISSUE TITLE
test(filesystem-sandbox-py): isError tests assert an SDK attribute name, not the wire flag — break on mcp 2.0.0's isError→is_error rename

### ISSUE THREAD

**Issue by jt-mchorse** [jt-mchorse/mcp-server-cookbook#134]
The `filesystem-sandbox-py` CI job installs `pip install -e '.[server,dev]'`, and the `server` extra pins `mcp>=1.27` with no upper bound. The MCP Python SDK has since released **2.0.0**, which renamed `CallToolResult`'s Python attribute `isError` → `is_error`. Both tests in `tests/test_server_iserror.py` read `result.isError` and now fail:

```
AttributeError: 'CallToolResult' object has no attribute 'isError'
```

Reproduced on unmodified `main` (@ 29373e7) with a clean Python 3.11 venv. The job is green today only because nothing has been pushed since 2026-07-20; it fails on the next push. This is the second unpinned-dependency break in this same job — the other is the ruff one in #132, different dependency and different fix.

## The production code is fine — this is test-only

Worth stating plainly, because the failure mode *looks* like the isError parity guarantee from #88 regressed. It did not. `CallToolResult` kept `isError` as the **wire alias** and sets `populate_by_name = True`, so `_wrap_dispatch_result`'s `types.CallToolResult(..., isError=is_error)` still constructs correctly, and the serialized payload an MCP client actually receives is unchanged:

```
# mcp 2.0.0, via _wrap_dispatch_result('sandbox_escape: /etc/hosts', True)
{'content': [{'type': 'text', 'text': 'sandbox_escape: /etc/hosts'}], 'isError': True, 'resultType': 'complete'}
```

Verified across both SDK majors:

| | mcp 1.29.0 | mcp 2.0.0 |
|---|---|---|
| Python attribute | `isError` | `is_error` |
| Wire alias | `isError` | `isError` |
| constructor `isError=` accepted | yes | yes (`populate_by_name`) |
| `model_dump(by_alias=True)["isError"]` | `True` | `True` |

## The real defect is what the test asserts on

`test_server_iserror.py` exists to lock the parity claim from #88 — *"the TS sibling returns `isError: true` on every refusal, and MCP clients key off that flag."* That is a claim about the **wire payload**. The tests assert on `result.isError`, a Python attribute name, which is an implementation detail of the SDK's pydantic model and not the contract at all. So the tests broke on an SDK rename while the contract they guard held perfectly.

Swapping to `result.is_error` would just move the brittleness — it would then fail on mcp 1.x, which is still inside the declared `mcp>=1.27` range.

## Proposed fix

Assert on the serialized form, `result.model_dump(by_alias=True)["isError"]`. That is version-stable across both majors (verified above), and it is literally what a client sees — so the test starts testing the actual #88 contract rather than a name.

Deliberately **not** changing `_wrap_dispatch_result`'s `isError=` constructor keyword: it works on both majors, whereas `is_error=` would break mcp 1.x. The alias is the more compatible choice here, not the less.

Pinning an upper bound on `mcp` in the `server` extra is the deeper fix, and it is the same portfolio-wide dependency-policy call as the ruff pin — tracked for JT in portfolio-ops#62. Not made unilaterally.

**Comment by jt-mchorse** [comment]
**Session plan** (~45 min)

**Will do:**
- Rewrite the two `_wrap_dispatch_result` assertions in `tests/test_server_iserror.py` to read the serialized wire payload (`model_dump(by_alias=True)["isError"]`) instead of the `result.isError` Python attribute, so the test locks the #88 parity contract rather than an SDK model's attribute name.
- Add a regression test asserting the constructor keyword `isError=` is accepted by whichever SDK major is installed — that is the compatibility hinge, since `is_error=` would break mcp 1.x.
- Extend the module docstring to record *why* the assertion is wire-level, so the next SDK rename doesn't tempt someone back to attribute access.
- Verify the whole suite green against **both** `mcp>=1.27,<2` (1.29.0) and `mcp` 2.0.0, on Python 3.11 and 3.12.
- Bump the `filesystem-sandbox-py` test count in the root README (`readme-check` job).

**Will defer:**
- Adding an upper bound to `mcp` in the `server` extra — same portfolio-wide dependency-policy call as the ruff pin, already tracked for JT in portfolio-ops#62. Not made unilaterally.
- Any change to `_wrap_dispatch_result` itself. Verified it produces the correct wire payload on both majors; the `isError=` constructor keyword is deliberately kept because it is the form that works on *both*, whereas `is_error=` would break mcp 1.x.
- mcp 2.0.0's new additive `resultType: 'complete'` wire field — additive and not part of any claim this repo makes.

**Decisions in flight:** none. Production behavior is unchanged and verified; this narrows a test to the contract it was always meant to guard.

**README impact:** updates the `filesystem-sandbox-py` test count (required by `readme-check`).

**Comment by jt-mchorse** [comment]
**Session close** (~40 min)

**Shipped:**
- Rewrote both `_wrap_dispatch_result` assertions to read the serialized wire payload (`model_dump(by_alias=True)["isError"]`) instead of the `result.isError` Python attribute — the test now locks the #88 parity contract rather than an SDK model's spelling.
- Added `test_wrapper_uses_the_constructor_keyword_that_works_on_both_sdk_majors`, pinning the compatibility hinge: `_wrap_dispatch_result` passes the `isError=` **alias**, deliberately, because `is_error=` would work on 2.x and break 1.x.
- Extended the module docstring with why the assertion is wire-level, so the next SDK rename doesn't tempt anyone back to attribute access.
- README test count 92 → 93.
- Verified the full suite green against **mcp 1.29.0 and 2.0.0**, on **Python 3.11 and 3.12**, plus `ruff check`/`format --check` clean on ruff 0.15.13 and 0.16.1.

**Production code unchanged.** Confirmed `_wrap_dispatch_result` emits an identical payload on both SDK majors; mcp 2.0.0 kept `isError` as the wire alias. The parity guarantee never regressed — only the test did, on a rename no client ever saw.

**Remaining for this issue:** none — ready for review.

**Merge order:** PR #135 is **based on #133's branch**, not `main`. #132 and #134 break the same CI job, so neither PR is green alone — #133 is red on `pytest` from this bug, and a `main`-based branch for this fix is red on `lint` from that one. Merge **#133 first**; GitHub retargets #135 to `main` automatically and it merges clean.

**Worth JT's attention:** this repo already enforces an SDK pin — `docs/spec-version.md` plus the `spec-version` CI job, which fails if any server drifts from `@modelcontextprotocol/sdk@^1.5.0`. That covers only the **TypeScript** servers. The Python port's `mcp>=1.27` sits entirely outside it, which is exactly how it drifted a full major unnoticed. Extending the existing check to the Python port reads more like completing a decision this repo already made than making a new one, but it needs a deliberate call on the target range — filing separately rather than doing it here. Related: portfolio-ops#62.

**Branch:** `session/2026-08-03-0717-issue-134` · **PR:** #135 (ready)

**% complete:** 100%
